### ISSUE TITLE
console_check_for_keypress failes with SIGSEGV

### ISSUE THREAD

**Issue by wizzardx** [Vladar4/libtcod_nim#7]
Trying to run a very basic project:

```
Traceback (most recent call last)
wizx_roguelike.nim(54)   wizx_roguelike
wizx_roguelike.nim(23)   handle_keys
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/home/david/learning/dev/LATER/roguelike_tutorials/BAD_roguelike_tutorial_in_nim/my_new_project/wizx-roguelike/src/wizx_roguelike '
       Tip: 8 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: "/home/david/dev/learning/misc/nim/github/Nim/bin/nim" c --noNimblePath --path:"/home/david/.nimble/pkgs/libtcod_nim-0.98" --path:"/home/david/.nimble/pkgs/sdl1-1.0.0" "-r"  "src/wizx_roguelike.nim"
```

Have attached wizx_roguelike.nim for reference.

Renamed to .nim.txt, since github doesn't like uploading of .nim files.

[wizx_roguelike.nim.txt](https://github.com/Vladar4/libtcod_nim/files/2344326/wizx_roguelike.nim.txt)

**Comment by Vladar4** [comment]
Shoud be fixed in v0.98.1. Please check if it is.

**Comment by wizzardx** [comment]
Get a different problem now with my 'wizx_roguelike.nim' example.

```
wizx_roguelike.nim(1, 8) Error: cannot open file: libtcod
```

I think that 'nimble install' doesn't install all the needed package files.

After installing libtcod_nim, these files are present under ~/.nimble/pkgs/libtcod_nim-0.98.1:

```
./nimblemeta.json
./libtcod_nim/private/parser.nim
./libtcod_nim/private/fov.nim
./libtcod_nim/private/image.nim
./libtcod_nim/private/sys.nim
./libtcod_nim/private/console_types.nim
./libtcod_nim/private/bsp.nim
./libtcod_nim/private/list.nim
./libtcod_nim/private/color.nim
./libtcod_nim/private/namegen.nim
./libtcod_nim/private/mouse_types.nim
./libtcod_nim/private/fov_types.nim
./libtcod_nim/private/txtfield.nim
./libtcod_nim/private/console.nim
./libtcod_nim/private/libtcod_define.nim
./libtcod_nim/private/lex.nim
./libtcod_nim/private/zip.nim
./libtcod_nim/private/bresenham.nim
./libtcod_nim/private/tree.nim
./libtcod_nim/private/mersenne_types.nim
./libtcod_nim/private/path.nim
./libtcod_nim/private/mersenne.nim
./libtcod_nim/private/mouse.nim
./libtcod_nim/private/noise.nim
./libtcod_nim/private/heightmap.nim
./libtcod_nim.nimble
```

I think this is related to another issue I saw when getting 'build_samples.sh' to run. I'll make a separate issue for that.

**Comment by Vladar4** [comment]
Looks like nimble don't download libtcod.nim
I'll look into it; you could download the file manually for now.

**Comment by wizzardx** [comment]
I've added more details in #10

**Comment by Vladar4** [comment]
Fixed in ed11a68f9cae49237466da5ff4efb0636e9571a4

**Comment by wizzardx** [comment]
Looks like the missing source code nim files are now installed (so, works for Nim 19.0, thanks!), and the samples are working fine, but I'm still getting (essentially) the original problem on my sample code:
```
Traceback (most recent call last)
wizx_roguelike.nim(54)   wizx_roguelike
wizx_roguelike.nim(23)   handle_keys
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/tmp/x/wizx_roguelike '
```

I'm running Debian Unstable, and so my installed version of libtcod is 1.7.0

**Comment by Vladar4** [comment]
I'm currently working on a libtcod 1.7.0 wrapper (not yet public), so wait for that if you don't want to use 1.5.1.

**Comment by Vladar4** [comment]
Should be fixed in [v0.99](https://github.com/Vladar4/libtcod_nim/releases/tag/v0.99).

Please feel free to open a new issue if you'll encounter some problem with the new version.
